# Generated by Django 5.2.1 on 2025-05-31 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenttask',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'managed': True, 'ordering': ['-submission_date']},
        ),
    ]
