# Generated by Django 5.1.4 on 2025-05-24 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_customuser_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='parent_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
    ]
