# Generated by Django 5.2.1 on 2025-05-31 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_branch_alter_customuser_branch_studentclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_book', to=settings.AUTH_USER_MODEL),
        ),
    ]
