# Generated by Django 5.1.4 on 2025-05-24 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_customuser_parent_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='parent_of',
        ),
        migrations.AddField(
            model_name='customuser',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
