# Generated by Django 5.2.1 on 2025-05-31 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_book_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='added_by',
        ),
    ]
