# Generated by Django 5.1.4 on 2025-05-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_remove_customuser_parent_of_customuser_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='parent',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
