# Generated by Django 5.2.1 on 2025-05-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_tasksubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
